<?php
/** @var CustomerHobby $customerHobbyViewModel */

use Test\Task\ViewModel\CustomerHobby;

$customerHobbyViewModel = $block->getData('customer_hobby_view_model');

$value = $customerHobbyViewModel->getHobbyValue();
$options = $customerHobbyViewModel->getHobbyOptions();
$storeLabel = $customerHobbyViewModel->getStoreLabel();

?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
</script>

<div class="customer-data" data-bind="scope: 'customer'">
    <form class="form form-edit-account"
          action="<?= $block->escapeUrl($block->getUrl('testtask/hobby/editPost')) ?>"
          method="post" id="form-customer-hobby"
          enctype="multipart/form-data"
          autocomplete="off">
        <fieldset class="fieldset info">
            <div class="field customer-hobby">
                <label class="label" for="customer-hobby">
                    <span><?= $block->escapeHtml($storeLabel) ?></span>
                </label>
                <div class="control">
                    <select id="customer-hobby" name="customer-hobby" title="<?= $block->escapeHtmlAttr($storeLabel) ?>"
                            data-bind="value:customer().hobby">
                        <?php foreach ($options as $option) : ?>
                            <option value="<?= $block->escapeHtmlAttr($option['value']) ?>"
                                <?= ($option['value'] == $value) ? ' selected="selected"' : '' ?>>
                                <?= $block->escapeHtml(__($option['label'])) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                        <span><?= $block->escapeHtml(__('Save')) ?></span>
                    </button>
                </div>
            </div>
            <?= $block->getBlockHtml('formkey') ?>
        </fieldset>
    </form>

</div>
